# Generated by Django 5.1.2 on 2024-10-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_assam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ASSAM',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
