# Generated by Django 5.1.3 on 2024-11-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_regis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regis',
            name='email',
        ),
        migrations.RemoveField(
            model_name='regis',
            name='tel',
        ),
    ]
